Repository wboka/learnxinyminutes-language-edition, pull requests merged in 2018-10, with the labels that each got.

#11 Added Esperanto numbers translation JSON
  .github/contributing.md
  README.md
  _data/en-de/basics.json
  _data/en-de/numbers.json
  _data/en-eo/numbers.json
  _data/en-es/numbers.json
Labels: en-eo, enhancement, good first issue

#18 [en-fr] Adding English to French Page
  _languages/en-fr.md
Labels: en-fr, website

#21 [website] Syncing Branches
  _data/en-eo/numbers.json
Labels: website

#25 [website] Updating New Language Instructions
  .github/contributing.md
Labels: website

#28 [website] Add TravisCI Integration
  .travis.yml
  Gemfile
  Gemfile.lock
Labels: website

#26 `[en-pt]` Created basic translations based on `[en-es]`JSONs
  README.md
  _data/en-es/voyage.json
  _data/en-pt/basics.json
  _data/en-pt/food.json
  _data/en-pt/greetings.json
  _data/en-pt/home.json
  _data/en-pt/numbers.json
  _data/en-pt/office.json
  _data/en-pt/restaurant.json
  _data/en-pt/travel.json
  _languages/en_pt.md
Labels: en-pt

#36 [en-es] Sync from master
  .github/contributing.md
  .travis.yml
  Gemfile
  Gemfile.lock
  README.md
  SUPPORT.md
  _config.yml
  _data/en-eo/numbers.json
  _data/en-es/voyage.json
  _data/en-fr/basics.json
  _data/en-fr/numbers.json
  _data/en-pt/basics.json
  _data/en-pt/food.json
  _data/en-pt/greetings.json
  _data/en-pt/home.json
  _data/en-pt/numbers.json
  _data/en-pt/office.json
  _data/en-pt/restaurant.json
  _data/en-pt/travel.json
  _languages/en_fr.md
  _languages/en_pt.md
  _layouts/default.html
  index.md
  templates/new-language.md
Labels: en-es

#34 [en-eo] Add more sections
  _data/en-eo/food.json
  _data/en-eo/greetings.json
  _data/en-eo/home.json
  _data/en-eo/office.json
Labels: en-eo
