Repository wboka/learnxinyminutes-language-edition, pull requests merged in 2019-10, with the labels that each got.

#45 [en-de] Add Travel
  _data/en-de/business.csv
  _data/en-de/greetings.csv
  _data/en-de/restaurant.csv
  _data/en-de/travel.csv
Labels: en-de

#46 Bring in changes from main development branch
  Gemfile.lock
  README.md
  _data/en-de/business.csv
  _data/en-de/food.csv
  _data/en-de/greetings.csv
  _data/en-de/home.csv
  _data/en-de/restaurant.csv
  _data/en-de/travel.csv
  _data/en-eo/food.json
  _data/en-eo/greetings.json
  _data/en-eo/home.json
  _data/en-eo/office.json
  _data/en-uk/basics.json
  _data/en-uk/food.json
  _data/en-uk/greetings.json
  _data/en-uk/home.json
  _data/en-uk/numbers.json
  _data/en-uk/office.json
  _data/en-uk/restaurant.json
  _data/en-uk/travel.json
  _languages/en_uk.md
  index.md
Labels: en-de

#47 [en-es] Add Questions
  _data/en-es/questions.csv
Labels: en-es, hacktoberfest

#48 [en-de] Fix translation direction
  _data/en-de/business.csv
  _data/en-de/restaurant.csv
  _data/en-de/travel.csv
Labels: en-de, hacktoberfest

#49 Bring in changes from main development branch
  Gemfile.lock
  README.md
  _data/en-es/questions.csv
  _data/en-uk/basics.json
  _data/en-uk/food.json
  _data/en-uk/greetings.json
  _data/en-uk/home.json
  _data/en-uk/numbers.json
  _data/en-uk/office.json
  _data/en-uk/restaurant.json
  _data/en-uk/travel.json
  _languages/en_uk.md
Labels: en-de

#50 Bring in changes from main development branch
  Gemfile.lock
  README.md
  _data/en-de/business.csv
  _data/en-de/food.csv
  _data/en-de/greetings.csv
  _data/en-de/home.csv
  _data/en-de/restaurant.csv
  _data/en-de/travel.csv
  _data/en-es/questions.csv
  _data/en-es/voyage.json
  _data/en-uk/basics.json
  _data/en-uk/food.json
  _data/en-uk/greetings.json
  _data/en-uk/home.json
  _data/en-uk/numbers.json
  _data/en-uk/office.json
  _data/en-uk/restaurant.json
  _data/en-uk/travel.json
  _languages/en_uk.md
  index.md
Labels: en-eo

#51 [en-eo] Add Colors and Restaurant
  _data/en-eo/colors.csv
  _data/en-eo/numbers.csv
  _data/en-eo/numbers.json
  _data/en-eo/restaurant.csv
Labels: en-eo, hacktoberfest

#52 [En_pt] Added two new section Fruits and vegetables
  _data/en-pt/fruits.json
  _data/en-pt/vegetables.json
Labels: en-pt

#53 [en-pt] feature: Adding [animals.json]
  _data/en-pt/animals.json
Labels: en-pt

#54 [en-fr] Fix French language; add several new topics
  _data/en-fr/basics.json
  _data/en-fr/food.json
  _data/en-fr/greetings.json
  _data/en-fr/home.json
  _data/en-fr/office.json
  _data/en-fr/restaurant.json
  _data/en-fr/travel.json
Labels: en-fr

#57 Some fixes for German
  _data/en-de/food.csv
  _data/en-de/greetings.csv
  _data/en-de/home.csv
  _data/en-de/restaurant.csv
  _data/en-de/travel.csv
Labels: en-de
